server:
  port: 8090
  
management:
  security:
    enabled: false  
  
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ksr4innovation/springcloudconfigrepo1
          deleteUntrackedBranches: true
          #username:
          #password:
          search-paths:
          - emp* 
          clone-on-start: true
          force-pull: true
          
       
           
              
           